### PR TITLE
Allow textbox customization, add text indexing, blah blah BLAH, character customization

### PR DESCRIPTION
**Pull request by MeowcaTheoRange**
Allow textbox customization, add text indexing, blah blah BLAH, character customization

### CODE REVIEW

**Comment by lajbel** [comment]
Things like `var` is not good for our js, let me add a format script

**Comment by lajbel** [comment]
Ready, update to master and run `npm run fmt`

**Comment by MeowcaTheoRange** [comment]
done

**Comment by lajbel** [comment]
And I think there is no need to put your sprites in the repo, I think I can take care of the demo sprites, thanks anyway!

**Comment by MeowcaTheoRange** [comment]
Ok, lol

**Pull request closed without merging**
